### ISSUE TITLE
What about NSKeyedArchiver?

### ISSUE THREAD

**Issue by joobei** [sylvaingml/Swift-array-encoding#1]
Sorry for posting here your blog doesn't allow comments. What happens if the root object you want to encode and save is an array of some custom type? Could you do the same stuff with NSKeyedArchiver.archiveRootObject() or would you have to make a class that wraps the array?

**Comment by sylvaingml** [comment]
Hi, it's fine.
I reply a bit late because I rarely check my Github messages :) 

Whatever kind of object you try to encode/decode they must implement the NSCoding protocol.

I did create an example playground [here](http://code.sylvaingamel.fr/swift,/nscoding/2016/03/22/Swift-NSCoding.html).

Have a look and as me if you have more questions.

**Comment by joobei** [comment]
Thanks for the reply. I have since found the answer sorry for not closing the issue. It is not possible to encode an array directly. Turns out one must recurse through each and every element and encode it one by one.
